import "./globals.css";
import { Inter } from "next/font/google"
import Providers from "@/providers/Providers"
import NavBar from "@/components/NavBar";
import { ModeToggle } from "@/components/toggleTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <nav className="h-16 px-4 flex justify-between border-b shadow-md select-none"><NavBar /><ModeToggle /></nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
